### ISSUE TITLE
How could I submit a new wasm runtime project?

### ISSUE THREAD

**Issue by alabulei1** [appcypher/awesome-wasm-runtimes#19]

**Comment by XCODEXYZ** [comment]
Would you take a new wasm role?

Live Life Happy 🌍❤️
Jonny@fluidrecruitment.co.uk
+447793841613 UK WhatsApp
https://www.linkedin.com/in/jdc123/
s: jonathon.cadden
t: @jonnyConnects<https://twitter.com/JonnyConnects>

Sent on the go from my iPhone, please excuse any typos

On 10 Feb 2020, at 08:41, alabulei1 <notifications@github.com> wrote:

﻿

**Comment by opendeepbay** [comment]
Yes. We are developing a Wasm compatible runtime engineered from ground up for server-side applications.  Here is the GitHub repo: https://github.com/second-state/SSVM.
Thanks!

**Comment by appcypher** [comment]
Thanks for the contribution
