### ISSUE TITLE
SSVM has been renamed to WasmEdge

### ISSUE THREAD

**Issue by andrewcfr** [appcypher/awesome-wasm-runtimes#30]
SSVM has been renamed to WasmEdge. See:

https://www.opensourceagenda.com/projects/ssvm/versions
0.8.0 (2021-05-13)
Breaking changes:
Renamed this project to WasmEdge (formerly ssvm).

https://github.com/WasmEdge/WasmEdge
WasmEdge (previously known as SSVM) is a lightweight, high-performance, and extensible WebAssembly runtime...

**Comment by appcypher** [comment]
Renamed
